/**
 * Represents a single security (stock) in an investment portfolio.
 */
export interface SecurityPosition {
    /** Stock ticker symbol (e.g., IBM, MSFT) */
    ticker: string;
    /** Target percentage of the portfolio (0 - 100) */
    targetPct: number;
    /** Current percentage of the portfolio (0 - 100) */
    currentPct: number;
    /** Deviation from target, provided as input data (Current % - Target %); not derived by the calculator */
    targetVariancePct: number;
    /** Current market price per share in USD */
    unitPrice: number;
}

/**
 * Configuration parameters for rebalancing calculations for an account.
 */
export interface RebalanceConfig {
    /** Total value of assets held in the account in USD */
    totalAssets: number;
    /** Whether the system allows trading fractional shares */
    allowFractional: boolean;
    /** Number of decimal places to use when rounding fractional shares (default: 2) */
    precision?: number;
}

/**
 * Direction of the trade action generated by the calculator.
 */
export type TradeAction = 'BUY' | 'SELL' | 'HOLD';

/**
 * Detailed trade instruction (calculation result) for a given security.
 */
export interface RebalanceInstruction {
    /** Stock ticker symbol (e.g., IBM, MSFT) */
    ticker: string;
    /** Deviation from the target percentage (Current % - Target %) */
    targetVariancePct: number;
    /** Calculated target value of the position in USD */
    targetValue: number;
    /** Current value of the position in USD */
    currentValue: number;
    /** Dollar amount needed to reach the target in USD */
    tradeValue: number;
    /** Calculated number of shares to buy (positive) or sell (negative) */
    sharesToTrade: number;
    /** Recommended action (BUY / SELL / HOLD) */
    action: TradeAction;
}